config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :products do
    resources :purchases
  end
  
  resources :reviews
  resources :stores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :bigint           not null, primary key
#  name       :string
#  price      :decimal(, )
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Product < ApplicationRecord
  has_many :purchases
  belongs_to :store
  
  validates :name, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  
  validate :quantity_within_limit
  
  def quantity_within_limit
    return unless quantity

    if quantity < 0
      errors.add(:quantity, 'too few')
    end
  end

end

app/models/purchase.rb
# == Schema Information
#
# Table name: purchases
#
#  id               :bigint           not null, primary key
#  delivery_address :string
#  quantity         :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  product_id       :bigint
#
# Indexes
#
#  index_purchases_on_product_id  (product_id)
#
# Foreign Keys
#
#  fk_rails_...  (product_id => products.id)
#
class Purchase < ApplicationRecord
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true }
  validates :delivery_address, presence: true

  # COMPLETED: Implement this logic
  # - Return true if a review for this purchase exists in the database 
  # - Return false otherwise
  def review_exist?
    return unless id
    @review = Review.find_by(purchase_id: id)
    if @review
      return true
    end
    false
  end
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id          :bigint           not null, primary key
#  comment     :string
#  rating      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  purchase_id :bigint
#
# Indexes
#
#  index_reviews_on_purchase_id  (purchase_id)
#
# Foreign Keys
#
#  fk_rails_...  (purchase_id => purchases.id)
#
class Review < ApplicationRecord
  belongs_to :purchase

  validates :rating, presence: true, numericality: { only_integer: true }
  validates :comment, presence: true

  validate :rating_within_limit
  
  def rating_within_limit
    return unless rating
    # COMPLETED: Implement validation logic for `rating`
    # - Rating cannot be greater than 5    
    # - Rating cannot be a negative number
    # - Handle any potential error/crash
    if rating > 5 || rating < 0
      errors.add("Rating cannot be greater than 5 and cannot be a negative ")
    end
  end
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id         :bigint           not null, primary key
#  name       :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Store < ApplicationRecord
    has_many :products

    validates :name, presence: true
    validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def error
    raise 'Test Error'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action do
    case action_name.to_sym
    when :new, :create
      @product = Product.new
    when :show, :edit, :update, :destroy
      @product = Product.find(params[:id])
    end
  end

  def new
    @store = []
    @stores = Store.select(:name, :id)
    @stores.each do |store|
      @store.append([store.name, store.id])
    end
  end

  def create
    @product.assign_attributes(product_params)
    if @product.save
      redirect_to products_url
    else
      flash[:error] = @product.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @rating = 0
    @length = 0
    
    @product.purchases.each do |purchase|
      @review  = Review.find_by(purchase_id: purchase.id)
      if @review
          if @review.rating != 0
            @rating += @review.rating
            @length += 1
          end
      end
    end

    if @length != 0
      @rating = @rating /  @length
    end
    
  end

  def index
    @products = Product.all    
  end

  private
    def product_params
      params.require(:product).permit(:name, :quantity, :price, :store_id)
    end
end  

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action do
    @product = Product.find(params[:product_id])

    case action_name.to_sym
    when :new, :create
      @purchase = @product.purchases.new
    when :show, :edit, :update, :destroy
      @purchase = @product.purchases.find(params[:id])
    end
  end

  def new
  end

  def create
    # COMPLETED: Also decrease product quantity.
    # - For example, if `purchase.quantity` is 3, decrease `product.quantity` by 3
    # - Display an error if `product.quantity` is less than 0 (negative number)
    @purchase.assign_attributes(purchase_params)

    @product.quantity = @product.quantity - @purchase.quantity
    if @product.quantity < 0
      flash[:error] = "Sorry out of stock"
      render :new
      return
    else
        @product.save
    end
    

    if @purchase.save
      redirect_to product_url(@product)
    else
      flash[:error] = @purchase.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    # COMPLETED: Show edit form
  end

  def update
    # COMPLETED: Update record (save to database)
    @updated_quantity = (@product.quantity + @purchase.quantity) - params[:purchase][:quantity].to_i
    if @updated_quantity <= 0 
      flash[:error] = "Sorry out of stock"
    end
    if @purchase.update(purchase_params)
      @product.quantity = @updated_quantity
      @product.save
      redirect_to product_url(@product), notice: "Purchase was updated succesfully"
    else
      render :edit
    end
  end

  def destroy
    # COMPLETED: Delete record
    @purchase.destroy
    redirect_to product_url(@product), notice: "Purchase was deleted succesfully"
  end

  def show    
    @review = Review.find_by(purchase_id: @purchase.id)
  end

  private
    def purchase_params
      params.require(:purchase).permit(:quantity, :delivery_address)
    end
end  

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action do
    case action_name.to_sym
    when :new, :create
      @review = Review.new
    end
  end

  def new     
    @review.assign_attributes(review_params) 
  end

  def create
    # COMPLETED: Create the record in database
    @review.assign_attributes(review_params) 
    if @review.save
      redirect_to product_purchase_path(params[:product_id], @review.purchase_id)
    else
      flash[:error] = @review.errors.full_messages.join(', ')
      render :new
    end
  end

  private
    def review_params
      params.require(:review).permit(:purchase_id, :rating, :comment)
    end
end

app/controllers/stores_controller.rb
# Completed: Implement 
class StoresController < ApplicationController
    before_action do
        case action_name.to_sym
        when :new, :create
          @store = Store.new
        when :show, :edit, :update, :destroy
          @store = Store.find(params[:id])
        end
      end
    
      def new
      end
    
      def create
        @store.assign_attributes(store_params)
        if @store.save
          redirect_to stores_url
        else
          flash[:error] = @store.errors.full_messages.join(', ')
          render :new
        end
      end
    
      def show
        @rating = 0
        @length = 0

        @store.products.each do |product|
            product.purchases.each do |purchase|
                @review  = Review.find_by(purchase_id: purchase.id)
                if @review
                    if @review.rating != 0
                      @rating += @review.rating
                      @length += 1
                    end
                end
              end
        end       
       
    
        if @length != 0
          @rating = @rating /  @length
        end
        
      end
    
      def index
        @stores = Store.all    
      end
    
      private
        def store_params
          params.require(:store).permit(:name, :url)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/format_helper.rb
module FormatHelper
  
  def format_price(price)
    # COMPLETED: Format the price. 
    # - Display a dollar sign
    # - Display two decimal places
    number_to_currency(price)
  end

end

app/views/home/index.html.erb
<div>

<ul>
<li><%= link_to 'Products', products_url %></li>
<li><%= link_to 'Stores', stores_url %></li>
</ul>

</div>

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <div style="margin-top: 10px;" class="error"><%= flash[:error] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductRating</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_url %>
    <br />
    <br />
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div>

<h1>Products</h1>

<ul>
<% @products.each do |product| %>
  <li><%= link_to product.name, product_url(product) %></li>
<% end %>
</ul>

<br />
<%= link_to 'Add Product', new_product_url %>

</div>

app/views/products/new.html.erb
<div>

<%= form_with model: @product, local: true do |f| %>
  <div style="margin-top: 10px;">
    <div><%= f.label :name %><div>
    <%= f.text_field :name %>
  </div>
  
  <div style="margin-top: 10px;">
    <div><%= f.label :price %><div>
    <%= f.text_field :price %>
  </div>
  
  <div style="margin-top: 10px;">
    <div><%= f.label :quantity %><div>
    <%= f.text_field :quantity %>
  </div>

  <div style="margin-top: 10px;">
    <div><%= f.label :store_id %><div>
    <div><%= f.select(:store_id, @store) %></div>
  </div>
  
  <div style="margin-top: 14px;">
    <%= f.submit "Create" %>
  </div>
<% end %>

</div>

app/views/products/show.html.erb
<div>
  <h1>Product #<%= @product.id %></h1>

  Name: <%= @product.name %>
  <br />
  Price: <%= format_price @product.price %>
  <br />
  Quantity: <%= @product.quantity %>
  <br />
  <%# COMEPLETED: Format the date time to make it more readable %> Posted on:
  <%= @product.created_at.strftime("%B %d, %Y, %A") %>
  <br />
  <%# COMPLETED: Calculate average rating based on the reviews from all of the
  product's purchases %> Average rating: <%= @rating %>

  <br />
  <br />
  <%= link_to 'Buy', new_product_purchase_url(@product) %>
</div>

<br />
<br />

<div>
  <h2>Purchases</h2>

  <ul>
    <% @product.purchases.each do |purchase| %>
    <li>
      <%= link_to "Purchase ##{purchase.id}", product_purchase_url(@product,
      purchase) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/purchases/_form.html.erb
<div>
  <%= form_with model: [@product, @purchase], local: true do |f| %>
  <div style="margin-top: 10px">
    <div>
      <%= f.label :quantity %>
      <div><%= f.text_field :quantity %></div>

      <div style="margin-top: 10px">
        <div>
          <%= f.label :delivery_address %>
          <div><%= f.text_area :delivery_address %></div>

          <div style="margin-top: 14px"><%= f.submit %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/purchases/edit.html.erb
<%= render "form" %>

app/views/purchases/new.html.erb
<%= render "form" %>

app/views/purchases/show.html.erb
<div>

<h1>Purchase #<%= @purchase.id %></h1>

Quantity: <%= @purchase.quantity %>
<br />
Address: <%= @purchase.delivery_address %>
<br />
<%# COMPLETED: Format the date time to make it more readable %>
Purchased at: <%= @purchase.created_at.strftime("%B %d, %Y, %A") %>

<br />
<br />

<%# COMPLETED: Open purchases#edit page %>
<%= link_to 'Edit', edit_product_purchase_url(@product, @purchase) %>

&nbsp;&nbsp;

<%# COMPLETED: Make a DELETE request to purchases#destroy %>
<%= link_to 'Delete', product_purchase_path(@product, @purchase), method: :delete, data: { confirm: "Are you sure?" } %>

</div>

<br />

<h2>Review</h2>

<% if @purchase.review_exist? %>
  <%# COMPLETED: Display the review here %>
 Rating: <%= @review.rating %>
 <br />
 Comment: <%= @review.comment %>

<% else %>
  <%= link_to 'Give a Review', new_review_path(product_id: 1, review: { purchase_id: @purchase.id }) %>
<% end %>

</div>

app/views/reviews/new.html.erb
<div>

<%= form_with model: @review, local: true do |f| %>
  <%= f.hidden_field :purchase_id %>
  <%= hidden_field_tag :product_id, params[:product_id] %>

  <div style="margin-top: 10px;">
    <div><%= f.label :rating %><div>
    <%= f.number_field :rating, in: 0..5 %>
  </div>
  
  <div style="margin-top: 10px;">
    <div><%= f.label :comment %><div>
    <%= f.text_field :comment %>
  </div>
  
  <div style="margin-top: 14px;">
    <%= f.submit "Submit" %>
  </div>
<% end %>

</div>

app/views/stores/index.html.erb
<div>

<h1>Stores</h1>

<%
  # COMPLETED: (Bonus Task) Implement complete store functionality
  # - Display all online stores here
  # - When clicked, go to stores#show page
  # - Add a link to create store
  # - Display store rating (based on the ratings from purchase reviews)
%>

<ul>
  <% @stores.each do |store| %>
    <li><%= link_to store.name, store_url(store) %></li>
  <% end %>
</ul>
  
<br />
<%= link_to 'Add Store', new_store_url %>

</div>

app/views/stores/new.html.erb
<div>
  <%= form_with model: @store, local: true do |f| %>
  <div style="margin-top: 10px">
    <div>
      <%= f.label :name %>
      <div><%= f.text_field :name %></div>

      <div style="margin-top: 10px">
        <div>
          <%= f.label :url %>
          <div><%= f.text_field :url %></div>

          <div style="margin-top: 14px"><%= f.submit "Create" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<div>
  <h1>Store #<%= @store.id %></h1>

  Name: <%= @store.name %>
  <br />
  Url: <%= @store.url %>
  <br />
  <br />
  Created at: <%= @store.created_at.strftime("%B %d, %Y, %A") %>
  <br />
  Average rating: <%= @rating %>

  <br />
  <br />
  <%= link_to 'Buy', new_product_url(@store) %>
</div>

<br />
<br />

<div>
  <h2>Products</h2>

  <ul>
    <% @store.products.each do |product| %>
    <li><%= link_to "Product ##{product.id}", product_url(product) %></li>
    <% end %>
  </ul>
</div>